name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          node-version: '16'

      - name: Build with Gradle
        run: |
          ./gradlew build

      - name: Run tests
        run: |
          ./gradlew test
