name: Java CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Run tests
        run: |
          chmod +x ./gradlew  # Grant execution permission
          ./gradlew test

  docker_build_push:
    runs-on: ubuntu-latest
    needs: build  # Detta jobb väntar på att "build"-jobbet slutförs
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub # Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Username for the Docker registry
          password: ${{ secrets.DOCKER_PAT }} # Personal Access Token (PAT) with access to the target repo

      - name: Build and push to Docker Hub # Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tompa123/docker-tdd-test:latest # Docker Hub repo name

  github_packages_push:
    runs-on: ubuntu-latest
    needs: build  # Detta jobb väntar på att "build"-jobbet slutförs
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages # Log in to GitHub Packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.pkg.github.com # GitHub Packages Docker registry URL
          username: ${{ github.actor }} # GitHub-användarnamn
          password: ${{ secrets.TOKEN_GITHUB }} # GitHub Personal Access Token (PAT)

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push to GitHub Packages # Build and push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: github_packages_push  # Detta jobb väntar på att "github_packages_push"-jobbet slutförs
    steps:
      - name: Deploy to testEnvironment
        run: echo "Deploying to testEnvironment"
