name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Run tests
        run: |
          chmod +x ./gradlew  # Grant execution permission
          ./gradlew test

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin docker.pkg.github.com
          docker build -t docker.pkg.github.com/king5tronk/tdduppift-gruppte/docker-tdd-test:latest -f path/to/Dockerfile .
          docker push docker.pkg.github.com/king5tronk/tdduppift-gruppte/docker-tdd-test:latest

      - name: Deploy to testEnvironment
        run: echo "Deploying to testEnvironment"
